### ISSUE TITLE
Option to open 'Code Peek' panel right below the focused line

### ISSUE THREAD

**Issue by ProLoser** [DFreds/code-peek-atom#10]
Similar to the behavior in brackets, instead of expanding the panel away from the cursor, it would be nice if it could be done closer to the cursor itself. One of the things brackets does is that it only peeks the function (not the entire file) and therefore there is no scrolling within the peek panel. It simply expands some lines in the middle of the document.

**Comment by DFreds** [comment]
This was the initial idea. I had some prototypes that would appear inline correctly, but for whatever reason, the text editor would not function properly. I haven't had time to figure out why. Feel free to try it  and make a pull request if you want! 

Otherwise, this isn't so much an issue as a feature request, so I'm going to close it.
